kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: demo-pod-rw
  namespace: default
rules:
  - verbs:
      - get
      - watch
      - list
    apiGroups:
      - ''
    resources:
      - pods
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-pod-rw-binding
  namespace: default
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: pod-ro-team
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: demo-pod-rw
