kind: Namespace
apiVersion: v1
metadata:
  name: dev-project-1
spec:
  finalizers:
    - kubernetes
---
apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: dev-project-1-argo
  namespace: dev-project-1
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-read-only
  namespace: dev-project-1
rules:
  - verbs:
      - get
      - watch
      - list
    apiGroups:
      - ''
    resources:
      - pods
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-read-only-binding
  namespace: dev-project-1
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: dev-project-1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-read-only
